name: cleanup

on: workflow_dispatch

jobs:
  TerraformDestroy:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: infra
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Create Image Tag
          run: |
            commit_count=$(git rev-list --count HEAD)
            commit_sha=$(git rev-parse --short HEAD)
            echo "IMAGE_TAG=$(echo $commit_count-$commit_sha)" >> $GITHUB_ENV

        - uses: hashicorp/setup-terraform@v1

        - name: Terraform init
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          run: terraform init -input=false -no-color

        - name: Terraform validation
          run: terraform validate

        - name: Terraform apply
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          run: terraform destroy -auto-approve -input=false -var "app_image_name=${{ env.IMAGE_TAG }}"